### ISSUE TITLE
Confusion over document and async support

### ISSUE THREAD

**Issue by iwillig** [funcool/suricatta#17]
Hi,
Really enjoying using suricatta in my project but I have the follow question.
I am trying to add support for async queries to my project The docs suggest to do the following,
```
(defn execute
  ([ctx q] (execute ctx q {}))
  ([ctx q opts]
   (let [act (.-act ctx)
         fun #(% (exc/try-on (sc/execute ctx q)))]
     (p/promise
      (fn [deliver]
        (send-off act (fn [_] (fun deliver))))))))

(defn fetch
  ([ctx q]
   (fetch ctx q {}))
  ([ctx q opts]
   (let [act (.-act ctx)
         fun #(% (exc/try-on (sc/fetch ctx q opts)))]
     (p/promise
      (fn [deliver]
        (send-off act (fn [_] (fun deliver))))))))
```
However I get the following error

`java.lang.IllegalArgumentException: No matching field found: act for class suricatta.types.Context`

So it seems like I don't have access to the actor for that type. I am assuming that `-act` is the actor we we use `send-off` later on.

I can see that the actor was refactor out in this commit, 
https://github.com/funcool/suricatta/commit/d599e22fbcf3cacf6081372ddd7fc7147a63c431
What is the correct way to support aysnc queries? Was this removal on purpose? 

Thanks

**Comment by niwinz** [comment]
Yes, it is a temporary change, but I pretty sure I will include (again) async support just out of the box.
For this moment you can use your own thread pool for schedule the blocking calls.

**Comment by iwillig** [comment]
Is your suggestion to follow what you been doing in the uxbox-backend project?
