### ISSUE TITLE
PSQLException The column index is out of range

### ISSUE THREAD

**Issue by smaant** [funcool/suricatta#6]
Hi. I was trying to use extended types and stumbled upon this problem.
In documentation you gives an example of extending types to support json. And it works perfectly if one inserts with raw sql (`insert into t1...`). However if one uses `insert-values`:
```clojure
(with-open [ctx (connection)]
  (sc/execute ctx (-> (dsl/insert-into :table)
                      (dsl/insert-values {:data {:a 1}}))))
```
It fails with exception:
```
2. Unhandled org.jooq.exception.DataAccessException
   SQL [insert into shipments (data) values ('{"a":1}'::jsonb)]; The
   column index is out of range: 1, number of columns: 0.

1. Caused by org.postgresql.util.PSQLException
   The column index is out of range: 1, number of columns: 0.
```
If I add `(fmt/get-sql)` after `insert-values` it'll work.

**Comment by smaant** [comment]
Also while investigating this I found NPE in this case:
```
(-> (dsl/insert-into :table)
    (dsl/insert-values {:data {:a 1}})
    (fmt/get-bind-values))
```
I traced it down to `bind` function in protocol extension for json, a statement (`stmt`) passed to this function is null.

**Comment by niwinz** [comment]
Thanks for report it.

**Comment by niwinz** [comment]
I have a proper solution for it but I need more time for test and make it ready, so I hope tomorrow will finish it. 

I should notice you that for some old design decisions the "extension" protocol is a little bit limited so for make it more powerfull and additionaly fix this bug, a little breaking api will be done.

**Comment by smaant** [comment]
This's awesome, I didn't expect a fix in such a short time!
I'm ok with a little api breaking, not sure about other library users.

**Comment by smaant** [comment]
Another NPE:
```clojure
(-> (dsl/create-table :db-test-table)
    (dsl/add-column :data {:type "json"})
    (fmt/get-sql))
```
I'm not sure if it suppose to work this way or not (with a type as just a string), but it seems like a good way to extend types.

**Comment by niwinz** [comment]
I have pushed the solution in the #7 PR, when tests are fixed I will merge it and deploy the snapshot.

**Comment by niwinz** [comment]
The api breakage lamentably is mandatory because the current impl is very limited.

**Comment by niwinz** [comment]
You can read the corresponding new documentation here: https://github.com/funcool/suricatta/blob/master/doc/content.adoc#custom-types

**Comment by smaant** [comment]
This NPE https://github.com/funcool/suricatta/issues/6#issuecomment-150140411 is still reproducible, should I create another issue?

**Comment by niwinz** [comment]
No, is still reproducible because you are no passing the dialect for rendering. In any case I will create an test case for it and analize if it is expected or not.

**Comment by niwinz** [comment]
I just have added a test case (https://github.com/funcool/suricatta/commit/5241a3953aefa630a800a8a08a82e294cb4768b4) for reproduce that and I didn't get any exception :S

**Comment by smaant** [comment]
Yeah, but it's another NPE :) I was talking about this:
```clojure
(-> (dsl/create-table :db-test-table)
    (dsl/add-column :data {:type "json"})
    (fmt/get-sql))
```

**Comment by niwinz** [comment]
You are using something that is not supported. The completed list of supported types is here: https://github.com/funcool/suricatta/blob/master/src/suricatta/dsl.clj#L38

In fact, the DDL statements lamentably are not as complete as I want and the related documentation does not specifies the supported types. This is one of the points for improvements.

**Comment by niwinz** [comment]
I have added an experimental support for user defined types and add the missing :pg/json type.
I mean with experimental because is not widely tested.

https://github.com/funcool/suricatta/commit/f4a4f7cc4fc8cebd649c64c56c24f19ac15d7d5b https://github.com/funcool/suricatta/commit/f936ebf018ed91ded42a3c526bfba370cfac2322

**Comment by smaant** [comment]
Cool! Could you push it into `0.6.0-SNAPSHPOT`?

**Comment by smaant** [comment]
Oh, it's already there! Thank man!

**Comment by smaant** [comment]
Hi man, I'm wondering if you are going to release a version with the latest changes soon? I'm going to release my code with your library and I'll have to hold it until you do it, because it'll not wise to release anything with a snapshot dependency.

**Comment by niwinz** [comment]
Yes, I have plans to do it in some days, but I'll try to find time for it today ;)

**Comment by smaant** [comment]
That would be awesome, thanks! You may also consider increasing first number to indicate incompatible api changes.

**Comment by niwinz** [comment]
The 0.6.0 version is released. The maturity of the library is documented and until 1.0.0 the minor version can contain minor breaking changes I think.  In any case, thanks for the suggestion.
